// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package synclet

import (
	"context"
	"github.com/windmilleng/tilt/internal/container"
	"github.com/windmilleng/tilt/internal/docker"
	"github.com/windmilleng/tilt/internal/k8s"
	"github.com/windmilleng/tilt/internal/k8s/cri"
)

// Injectors from wire.go:

func WireDockerSynclet(ctx context.Context, env k8s.Env, runtime container.Runtime) (*DockerSynclet, error) {
	cli, err := docker.DefaultClient(ctx, env, runtime)
	if err != nil {
		return nil, err
	}
	dockerSynclet := NewDockerSynclet(cli)
	return dockerSynclet, nil
}

func WireCriSynclet(ctx context.Context, criEndpoint cri.Endpoint) (*CriSynclet, error) {
	cliClient := cri.NewCliClient(criEndpoint)
	criSynclet := NewCriSynclet(cliClient)
	return criSynclet, nil
}
